export { default as Home } from './Home'
export { default as About } from './About'
export { default as Dashboard } from './Dashboard'
export { default as Profile } from './Profile'
export { default as SignUp } from './SignUp'
export { default as Login } from './Login'
