services:
  postgres:
    container_name: oailee-postgres
    image: postgres
    environment:
      POSTGRES_USER: oailee-admin
      POSTGRES_PASSWORD: N0name6355
      POSTGRES_DB: oailee
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: